version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: option-t
    versions:
    - 24.1.0
    - 25.0.2
    - 25.0.4
    - 25.2.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.28
    - 14.14.31
    - 14.14.32
    - 14.14.34
    - 14.14.35
    - 14.14.37
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@types/yargs"
    versions:
    - 15.0.12
    - 16.0.0
  - dependency-name: globby
    versions:
    - 11.0.2
  - dependency-name: lodash
    versions:
    - 4.17.20
