version: 2

jobs:
    prepare:
        docker:
            - image: circleci/node:10.8.0-stretch-browsers

        steps:
            - checkout
            - run:
                name: Install dependencies
                command: yarn
            - persist_to_workspace:
                root: .
                paths:
                    - "./*"

    test:
        docker:
            - image: circleci/node:10.8.0-stretch-browsers

        steps:
            - attach_workspace:
                at: .
            - run:
                name: Lint scripts
                command: npm run lint
            - run:
                name: Check formatted sources
                command: npm run check_format
            - run:
                name: Run unit testing
                command: npm test

workflows:
    version: 2
    test:
        jobs:
            - prepare
            - test:
                requires:
                    - prepare
