version: 2

jobs:
    prepare:
        docker:
            - image: circleci/node:13.1.0-stretch-browsers

        steps:
            - checkout
            - run:
                  name: Install dependencies
                  command: yarn
            - persist_to_workspace:
                  root: .
                  paths:
                      - './*'

    test:
        docker:
            - image: circleci/node:13.1.0-stretch-browsers

        steps:
            - attach_workspace:
                  at: .
            - run:
                  name: Lint scripts
                  command: npm run lint
            - run:
                  name: Check formatted sources
                  command: npm run check_format
            - run:
                  name: Builing scripts
                  command: npm run build
            - run:
                  name: Run unit testing
                  command: npm test

    publish:
        docker:
            - image: circleci/node:13.1.0-stretch-browsers

        steps:
            - attach_workspace:
                  at: .
            - run:
                  name: Create npmrc file
                  command: touch ~/.npmrc
            - run:
                  name: Write token to npmrc file
                  command: echo "//registry.npmjs.org/:_authtoken=${NPMJS_PUBLISH_TOKEN}" >> ~/.npmrc
            - run:
                  name: Can package publish to npm?
                  command: npm run can-npm-publish
            - run:
                  name: Publish to npm
                  command: npm publish echo "//registry.npmjs.org/:_authtoken=${NPMJS_PUBLISH_TOKEN}" >> ~/.npmrc

workflows:
    version: 2
    flows:
        jobs:
            - prepare
            - test:
                  requires:
                      - prepare
            - publish:
                  requires:
                      - test
                  filters:
                      branches:
                          only: master
