version: 2

jobs:
    prepare:
        docker:
            - image: circleci/node:13.1.0-stretch-browsers

        steps:
            - checkout
            - run:
                  name: Install dependencies
                  command: yarn
            - persist_to_workspace:
                  root: .
                  paths:
                      - './*'

    build:
        docker:
            - image: circleci/node:13.1.0-stretch-browsers

        steps:
            - attach_workspace:
                  at: .
            - run:
                  name: Builing scripts
                  command: npm run build
            - persist_to_workspace:
                  root: .
                  paths:
                      - './*'

    lint:
        docker:
            - image: circleci/node:13.1.0-stretch-browsers
        steps:
            - attach_workspace:
                  at: .
            - run:
                  name: Lint scripts
                  command: npm run lint

    check_format:
        docker:
            - image: circleci/node:13.1.0-stretch-browsers
        steps:
            - attach_workspace:
                  at: .
            - run:
                  name: Check formatted sources
                  command: npm run check_format

    test:
        docker:
            - image: circleci/node:13.1.0-stretch-browsers

        steps:
            - attach_workspace:
                  at: .
            - run:
                  name: Run unit testing
                  command: npm test

    can_publish:
        docker:
            - image: circleci/node:13.1.0-stretch-browsers

        steps:
            - attach_workspace:
                  at: .
            - run:
                  name: Can package publish to npm?
                  command: npm run can-npm-publish

    publish:
        docker:
            - image: circleci/node:13.1.0-stretch-browsers

        steps:
            - attach_workspace:
                  at: .
            - run:
                  name: Create npmrc file
                  command: touch ~/.npmrc
            - run:
                  name: Write token to npmrc file
                  command: |
                      echo "//registry.npmjs.org/:_authToken=${NPMJS_PUBLISH_TOKEN}" >> ~/.npmrc
                      npm whoami
            - run:
                  name: Publish to npm
                  command: npm publish --access=public

workflows:
    version: 2
    flows:
        jobs:
            - prepare
            - build:
                  requires:
                      - prepare
            - can_publish:
                  requires:
                      - prepare
                  filters:
                      branches:
                          only: master
            - check_format:
                  requires:
                      - prepare
            - lint:
                  requires:
                      - prepare
            - test:
                  requires:
                      - build
            - publish:
                  requires:
                      - can_publish
                      - check_format
                      - lint
                      - test
                  filters:
                      branches:
                          only: master
